<?php
/**
 * Campos que un administrador puede editar en financiamiento_registros (Sol Financiamiento).
 * No incluye firma ni telemetría. Debe coincidir con columnas reales de la tabla.
 */
return [
    'columnas_editables' => [
        'token_email', 'email_vendedor', 'id_vendedor',
        'cliente_nombre', 'cliente_estado_civil', 'cliente_sexo', 'cliente_id', 'cliente_nacimiento', 'cliente_edad',
        'cliente_nacionalidad', 'cliente_dependientes', 'cliente_correo', 'cliente_peso', 'cliente_estatura',
        'vivienda', 'vivienda_monto', 'prov_dist_corr', 'tel_residencia', 'barriada_calle_casa', 'calle', 'celular_cliente',
        'edificio_apto', 'correo_residencial',
        'empresa_nombre', 'empresa_ocupacion', 'empresa_anios', 'empresa_telefono', 'empresa_salario', 'empresa_direccion',
        'otros_ingresos', 'ocupacion_otros', 'trabajo_anterior',
        'tiene_conyuge',
        'con_nombre', 'con_estado_civil', 'con_sexo', 'con_id', 'con_nacimiento', 'con_edad',
        'con_nacionalidad', 'con_dependientes', 'con_correo', 'con_empresa', 'con_ocupacion', 'con_anios', 'con_tel',
        'con_salario', 'con_direccion', 'con_otros_ingresos', 'con_trabajo_anterior',
        'refp1_nombre', 'refp1_cel', 'refp1_dir_res', 'refp1_dir_lab',
        'refp2_nombre', 'refp2_cel', 'refp2_dir_res', 'refp2_dir_lab',
        'reff1_nombre', 'reff1_cel', 'reff1_dir_res', 'reff1_dir_lab',
        'reff2_nombre', 'reff2_cel', 'reff2_dir_res', 'reff2_dir_lab',
        'marca_auto', 'modelo_auto', 'anio_auto', 'kms_cod_auto', 'precio_venta', 'abono',
        'sucursal', 'nombre_gestor', 'comentarios_gestor',
    ],
    'labels' => [
        'token_email' => 'Token enlace (email codificado)',
        'email_vendedor' => 'Email vendedor (enlace)',
        'id_vendedor' => 'ID vendedor (ejecutivos_ventas)',
        'cliente_nombre' => 'Nombre', 'cliente_estado_civil' => 'Estado civil', 'cliente_sexo' => 'Sexo',
        'cliente_id' => 'Cédula', 'cliente_nacimiento' => 'Nacimiento', 'cliente_edad' => 'Edad',
        'cliente_nacionalidad' => 'Nacionalidad', 'cliente_dependientes' => 'Dependientes', 'cliente_correo' => 'Correo',
        'cliente_peso' => 'Peso', 'cliente_estatura' => 'Estatura',
        'vivienda' => 'Vivienda', 'vivienda_monto' => 'Monto vivienda', 'prov_dist_corr' => 'Prov./Dist./Corr.',
        'tel_residencia' => 'Tel. residencia', 'barriada_calle_casa' => 'Dirección', 'calle' => 'Calle',
        'celular_cliente' => 'Celular', 'edificio_apto' => 'Edificio/Apto', 'correo_residencial' => 'Correo residencial',
        'empresa_nombre' => 'Empresa', 'empresa_ocupacion' => 'Ocupación', 'empresa_anios' => 'Años empresa',
        'empresa_telefono' => 'Tel. empresa', 'empresa_salario' => 'Salario', 'empresa_direccion' => 'Dir. empresa',
        'otros_ingresos' => 'Otros ingresos', 'ocupacion_otros' => 'Ocupación otros', 'trabajo_anterior' => 'Trabajo anterior',
        'tiene_conyuge' => 'Tiene cónyuge (0/1)',
        'con_nombre' => 'Cónyuge nombre', 'con_estado_civil' => 'Cónyuge estado civil', 'con_sexo' => 'Cónyuge sexo',
        'con_id' => 'Cónyuge cédula', 'con_nacimiento' => 'Cónyuge nacimiento', 'con_edad' => 'Cónyuge edad',
        'con_nacionalidad' => 'Cónyuge nacionalidad', 'con_dependientes' => 'Cónyuge dependientes', 'con_correo' => 'Cónyuge correo',
        'con_empresa' => 'Cónyuge empresa', 'con_ocupacion' => 'Cónyuge ocupación', 'con_anios' => 'Cónyuge años',
        'con_tel' => 'Cónyuge tel.', 'con_salario' => 'Cónyuge salario', 'con_direccion' => 'Cónyuge dirección',
        'con_otros_ingresos' => 'Cónyuge otros ingresos', 'con_trabajo_anterior' => 'Cónyuge trabajo anterior',
        'refp1_nombre' => 'Ref. personal 1 nombre', 'refp1_cel' => 'Ref. personal 1 cel', 'refp1_dir_res' => 'Ref. p.1 dir. res.',
        'refp1_dir_lab' => 'Ref. p.1 dir. lab.', 'refp2_nombre' => 'Ref. personal 2 nombre', 'refp2_cel' => 'Ref. p.2 cel',
        'refp2_dir_res' => 'Ref. p.2 dir. res.', 'refp2_dir_lab' => 'Ref. p.2 dir. lab.',
        'reff1_nombre' => 'Ref. familiar 1', 'reff1_cel' => 'Ref. f.1 cel', 'reff1_dir_res' => 'Ref. f.1 dir. res.',
        'reff1_dir_lab' => 'Ref. f.1 dir. lab.', 'reff2_nombre' => 'Ref. familiar 2', 'reff2_cel' => 'Ref. f.2 cel',
        'reff2_dir_res' => 'Ref. f.2 dir. res.', 'reff2_dir_lab' => 'Ref. f.2 dir. lab.',
        'marca_auto' => 'Marca', 'modelo_auto' => 'Modelo', 'anio_auto' => 'Año', 'kms_cod_auto' => 'Km',
        'precio_venta' => 'Precio venta', 'abono' => 'Abono',
        'sucursal' => 'Sucursal', 'nombre_gestor' => 'Gestor', 'comentarios_gestor' => 'Comentarios gestor',
    ],
    'textarea' => ['comentarios_gestor', 'empresa_direccion', 'con_direccion', 'barriada_calle_casa', 'prov_dist_corr'],
    'number' => [
        'id_vendedor', 'cliente_edad', 'cliente_dependientes', 'cliente_peso', 'cliente_estatura',
        'vivienda_monto', 'empresa_anios', 'empresa_salario', 'con_edad', 'con_dependientes', 'con_salario',
        'anio_auto', 'kms_cod_auto', 'precio_venta', 'abono',
    ],
    'date' => ['cliente_nacimiento', 'con_nacimiento'],
];
